### ISSUE TITLE
Unable to run google-analytics-extractor

### ISSUE THREAD

**Issue by mamreezaa** [keboola/google-analytics-extractor#10]
**Preconditions**
-PHP 7.1
-apache2 2.4.18 (Ubuntu)
-Linux 

**What i did**
i am following the instruction given in https://github.com/keboola/google-analytics-extractor to run this application. but always i am come up with the following output

'[2017-05-15 15:54:43] ex-google-analytics.WARNING: You don't have access to Google Analytics resource. Probably you don't have access to profile, or profile doesn't exists anymore. [] []
Extractor finished successfully.'

1. I can make sure the profile is exist and the yml configuration are correct.
2. i checked my profile configuration by using this https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/profiles/get GA API caller and this api returning 200 status code. 
3. The oauth are correct. i have create new api in developer.console and i have generate tokens.

**What i want**
Can someone explain me how to run the application successfully?

**Comment by MiroCillik** [comment]
Sorry Mamreezaa I didn't get back to you. If you still want to use our extractor, please reopen this issue and I will write you instructions.
