### ISSUE TITLE
Collisions in data hashed ids

### ISSUE THREAD

**Issue by MiroCillik** [keboola/google-analytics-extractor#19]
![ga_hash_collisions](https://user-images.githubusercontent.com/1488015/36677293-14ceea60-1b0e-11e8-8421-0945e64bbb64.png)

**Comment by MiroCillik** [comment]
Bude potreba:
 - [ ] pridat delimiter do vstupu do hash funkcie (https://github.com/keboola/google-analytics-extractor/compare/collision?expand=1)
 - [ ] upravit prefix output bucketu
 - [ ] zalozit novu komponentu `ex-google-analytics-v5` v Developer Portali
 - [ ] pripravit migracny tool (mal fungovat genericky, staci len skopirovat konfiguraciu)
 - [ ] upravit UI pre migracnu tool
 - [ ] post na status

**Comment by MiroCillik** [comment]
Nakoniec sme to s Padakom vymysleli tak, ze v kode bude if, ktory pre data do urciteho datumu pouzije "stary" PK a pre data od tohto datumu pouzije "novy" PK.
Zaroven sa do novyh konfiguracii ulozi priznak, takze bude jasne, ze ide o novu konfiguraciu a aj historicke data moze ukladat s novym PK.

**Comment by ondrejhlavacek** [comment]
GA vždycky stahují data agregovaný na den? Na týden/měsíc/rok nestahují?

**Comment by MiroCillik** [comment]
@ondrejhlavacek mozu, ale presiel som vsetky konfigurace (cez Shared Config), ktore neobsahuju dimenziu `date`. A v podstate tam take konfiguracie neexistuju. Takze pokial vznikne nova konfiguracia, kde nebude dimenzia `date`, pouzije sa "novy" PK.

**Comment by ondrejhlavacek** [comment]
Tak je tam ta dimenze `date` vůbec potřeba? :-) Byl by kratší if.

**Comment by MiroCillik** [comment]
Ja myslim, ze to tam musi byt :) Pokial nie je nastavane dimenzia `date`, pouzije sa novy PK. Pokial je nastavena dimenzia `date` a datum je mensi nez ..., pouzije sa stary PK.

https://github.com/keboola/google-analytics-extractor/commit/0c0b35ac1827f2a527bf9f51add174001e25a511#diff-8e2ef77ebc5ff7c5129e4e45250db91aR109

Zaroven sa k novym konfigom prida ten priznak, takze dufam, ze od nejakeho momentu v buducnosti, sa tento "if" bude moct vyhodit <= vsetky konfigy budu mat tento priznak.
Alebo vznikne nejaka uplne nova verzia..

**Comment by MiroCillik** [comment]
BTW: Teraz tam mam nastaveny datum 20.3., ale momentalne sa to deployuje do apky `keboola.ex-google-analytics-v5`, ktora je skryta. Na tej to zajtra finalne otestujem, potom ak to bude OK, ten datum posuniem napr. o tyzden a nasadim to do aktualnej apky `v4`.

**Comment by MiroCillik** [comment]
Skontrolovane, vyzera to dobre, nasadil som to teda a "datum" nastavil na 27.3.2018.

Este bude potom potreba pridat do UI ten priznak, ale to az po 27om.

**Comment by MiroCillik** [comment]
Vyzera to byt OK, zatvaram
