### ISSUE TITLE
Sample action uses only first profile

### ISSUE THREAD

**Issue by Halama** [keboola/google-analytics-extractor#27]
Klient reportovat že test query při vybranách `--all-profiles` vrací prázdná data ale pokud se spustí job tak to data vrací.

Je to tím že v sample akci se bere první profil https://github.com/keboola/google-analytics-extractor/blob/5f028abbf04b1ac99ce9ac5d6870428ad4c4f692/src/Keboola/GoogleAnalyticsExtractor/Application.php#L157

Nejspíše by se tomu mělo přizpůsobt UI a upozornit že náhled je pouze pro vybraný (nebo první) profil?

**Comment by kacurez** [comment]
vobec si nespominam preco by tam mal byt prave prvy profil ani nato teraz nevidim dovod. Imho by to spravne malo brat vybrany profil a v pripade ze su vybrate vsetky tak ten prvy. Mozno si spomenie @MiroCillik ?

**Comment by Halama** [comment]
tak se to chová jak popisuješ.

**Comment by Halama** [comment]
Problém je v tom že to vezme ten první kdyz jsou vybrané všechny a neřekne to.

**Comment by kacurez** [comment]
aha jasne, tak to poriesim v ui :)

**Comment by MiroCillik** [comment]
Dovod na to je jednoduchy, to preview vracia len prvych 50 riadkov, tak naco stahovat dalsie profily, ked mi staci 50 riadkov z prveho profilu? Problem je len v pripade, ked ten prvy profil nevrati nic :)

**Comment by Halama** [comment]
problem je jenom v tom ze to nerekne ze to bere z prvniho profilu a to se fixne v ui.

**Comment by MiroCillik** [comment]
A mame na to issue v UI @kacurez ?

**Comment by Halama** [comment]
https://github.com/keboola/kbc-ui/issues/1867

**Comment by Halama** [comment]
založil jsem to první tady a až pak po debugu mi došlo že to bude spíš na ui. Takže tady se to imho může zavřít
