### ISSUE TITLE
get sample data docker sync action

### ISSUE THREAD

**Issue by kacurez** [keboola/google-analytics-extractor#4]
z https://github.com/keboola/kbc-ui/issues/568
`oproti původnímu exploreru mi tu schází možnost vidět co moje query vrátí - nějakej sample dat.`
Pri buildovani query backend umozni vratit sample dat, imo by mal byt vzdy pevne dany pocet samplov napr na 10. 
Urobit to ako docker sync action.

**Comment by MiroCillik** [comment]
Spravene.
