### ISSUE TITLE
MCF: Requested Resource Too Large to Return

### ISSUE THREAD

**Issue by ujovlado** [keboola/google-analytics-extractor#47]
```
Report contains sampled data. Sampling rate is 120%.\nReport contains sampled data. Sampling rate is 120%.
```

`docker-cabd40dd18dbb03e6a7536fcb3f3a4f7`

**Comment by ujovlado** [comment]
Neviem ci to ma pokracovat (mozno ano) ale nemalo by to skoncit ako app error.

**Comment by ujovlado** [comment]
- https://keboola.slack.com/archives/C09U3R1J4/p1561454543008300
- https://keboola.slack.com/archives/C09U3R1J4/p1561456573008400

Este sa tam pise nieco o `Requested Resource Too Large to Return`

**Comment by MiroCillik** [comment]
Hmm, tyka sa to MCF API
