### ISSUE TITLE
RESOURCE_EXHAUSTED user exception

### ISSUE THREAD

**Issue by MiroCillik** [keboola/google-analytics-extractor#7]
http://stackoverflow.com/questions/41457363/what-is-the-reason-for-the-error-resource-exhausted

**Comment by MiroCillik** [comment]
https://www.hitchhq.com/googleanalytics/activities/api-limits-and-quotas-analytics-metadata-api-google-developers-57f2499e224ae0ce476cbb5a

**Comment by ondrejhlavacek** [comment]
Stalo se to znovu 
https://connection.keboola.com/admin/utils/logs?file=2017/05/03/09/2017-05-03-09-43-34-59098a26d3fb9-exception

**Comment by ondrejhlavacek** [comment]
A znovu 
https://connection.keboola.com/admin/utils/logs?file=2017/05/31/08/2017-05-31-08-03-31-592e5cb3a68d7-exception

**Comment by ondrejhlavacek** [comment]
A znovu
https://connection.keboola.com/admin/utils/logs?file=2017/05/31/08/2017-05-31-08-03-31-592e5cb3a68d7-exception

**Comment by MiroCillik** [comment]
Mam to v pipeline :) Snad sa k tomu coskoro dostanem
